import '@/styles/globals.css'
import { SWRConfig } from 'swr'
import { ErrorBoundary } from 'react-error-boundary'
import ErrorFallback from '@/components/ErrorFallback'
import { fetchData } from '@/utils/api'
import { Global } from '@emotion/react'
import globalStyles from '@/styles/globalStyles'
import Head from 'next/head'
import Wrap from '@/components/layout/Wrap'

export default function App({ Component, pageProps }) {
  return (
    <ErrorBoundary
      FallbackComponent={ErrorFallback}
      onError={(error, info) => {
        console.error('ErrorBoundary caught an error', error, info)
      }}
    >
      <SWRConfig
        value={{
          // refreshInterval: 3000,
          fetcher: fetchData
        }}
      >
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Global styles={globalStyles} />
        <Wrap>
          <Component {...pageProps} />
        </Wrap>
      </SWRConfig>
    </ErrorBoundary>
  )
}
