import { fetchData } from '@/lib/axiosInstance';
import useSWR from 'swr';
import Container from '@/components/layout/Container';
import Header from '@/components/layout/Header';
import Head from 'next/head';
import Footer from '@/components/layout/Footer';
import { useEffect } from 'react';

export async function getServerSideProps() {
  const initialData = await fetchData(`/users`);
  return {
    props: {
      initialData,
    },
  };
}

export default function UsersPage({ initialData }) {
  const { data, error, isLoading, isValidating } = useSWR('/users', {
    fallbackData: initialData,
  });

  useEffect(() => {
    console.log('isLoading', isLoading);
  }, [isLoading]);

  useEffect(() => {
    console.log('isValidating', isValidating);
  }, [isValidating]);

  return (
    <>
      <Head>
        <title>Create Next App22</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <h1>Users</h1>
        <ul>
          {data.map((user) => (
            <li key={user.id}>
              {user.name} ({user.email})
            </li>
          ))}
        </ul>
      </Container>
      <Footer />
    </>
  );
}
